### ISSUE TITLE
Inclusion of "collections" package breaks my project unit tests

### ISSUE THREAD

**Issue by dgg** [mqttjs/MQTT.js#1392]
Starting with 4.3.0 the library takes a dependency on the collections package.
I can't find any references to such package, but I suspect that is because it "patches" (modifies the prototype) of several objects, so I cannot suggest a different way to do things without taking that dependency.

The errors I am getting are the same as the ones described in: https://github.com/sinonjs/commons/issues/18, however I cannot workaround them as suggested.

I would really like to upgrade to the latest version, but as of now, I have to stay in 4.2.8 as it does not take dependency on the collections library).
I'd really like to suggest eliminating the dependency on a library that is prone to break other people's code due to their modification of prototypes (https://github.com/montagejs/collections/issues?q=is%3Aissue+is%3Aopen+break).
Maybe I could give a hand if I knew what the package is used for.

Thanks in advance

**Comment by redboltz** [comment]
#1386 updates collections.js It might help to solve your problem.

See
https://github.com/mqttjs/MQTT.js/pull/1386#issuecomment-1002465630
https://github.com/mqttjs/MQTT.js/pull/1301#issuecomment-1002407521

> collections.js updates Array.
> I personally think that updating (overwriting) intrinsic Array.from() is not good way. I guess that there is some historycal reason (older browser support?).

https://github.com/montagejs/collections/issues/241#issuecomment-1002391980

As I commented, updating the intrinsic container (Array) is not good.
So I'm looking for replacement candidate.

But collections.js mentioned 

> Design principles
> extends core types (e.g extends Array.prototype with additional non-enumerable properties like .set)
https://www.npmjs.com/package/collections

I think that it is very limited extention. However, if we get the same functionality without intrinsic library such as Array, it is better.

> Maybe I could give a hand if I knew what the package is used for.

Thank you. collections is used for two purposes. One is LRU map, the other is SortedSet.
Let me describe how they are used.

----

# LRU map https://www.collectionsjs.com/lru-map
See https://github.com/mqttjs/MQTT.js/blob/f04c24bd082aa9f6db2da6da65e40b2e0b692bcc/lib/topic-alias-send.js
It is used for TopicAlias management.
Topic Alias is 16bit number https://docs.oasis-open.org/mqtt/mqtt/v5.0/os/mqtt-v5.0-os.html#_Toc3901113
It requires the following operation.

### get
https://github.com/mqttjs/MQTT.js/blob/f04c24bd082aa9f6db2da6da65e40b2e0b692bcc/lib/topic-alias-send.js#L38

Get value from key with touch (Use updating)

### set
https://github.com/mqttjs/MQTT.js/blob/f04c24bd082aa9f6db2da6da65e40b2e0b692bcc/lib/topic-alias-send.js#L38

### length
https://github.com/mqttjs/MQTT.js/blob/f04c24bd082aa9f6db2da6da65e40b2e0b692bcc/lib/topic-alias-send.js#L45

### clear
https://github.com/mqttjs/MQTT.js/blob/f04c24bd082aa9f6db2da6da65e40b2e0b692bcc/lib/topic-alias-send.js#L77

Overwriting by new object is acceptable solution.

### get least used element
https://github.com/mqttjs/MQTT.js/blob/f04c24bd082aa9f6db2da6da65e40b2e0b692bcc/lib/topic-alias-send.js#L90

It is not commonly supported. But it is very important feature to implement Topic Alias.

----

One candidate I found is https://www.npmjs.com/package/quick-lru. I think that it is covered full required functionality.
"get least used element" is achieved by `.entriesAscending()` or `.entriesDescending()`.
Looks nice. However, it doesn't seems to support common js. It is a problem.
It seems that https://github.com/mqttjs/MQTT.js/tree/vNext doesn't need common js support but for the current master, it is required, IIUC.

# Sorted Set https://www.collectionsjs.com/sorted-set
It is used for unique (unconflict) messageId (Packet Identifier) allocation.
I asked JavaScript SortedSet on https://stackoverflow.com/questions/65948823/sorted-ordered-collection-for-javascript

### length
https://github.com/redboltz/number-allocator/blob/af3e1542b01910626aa9237f0ebb8f2493c2a288/lib/number-allocator.js#L58
```js
  if (this.ss.length === 0) return null
```

### get minimum element
https://github.com/redboltz/number-allocator/blob/af3e1542b01910626aa9237f0ebb8f2493c2a288/lib/number-allocator.js#L72
```js
  const it = this.ss.min()
```
### delete minimum element
https://github.com/redboltz/number-allocator/blob/af3e1542b01910626aa9237f0ebb8f2493c2a288/lib/number-allocator.js#L80
```js
    this.ss.shift()
```

Erase specific element by iterator (cursor) or key can be used.

### get matched element otherwise the next element
https://github.com/redboltz/number-allocator/blob/af3e1542b01910626aa9237f0ebb8f2493c2a288/lib/number-allocator.js#L95
```js
  const it = this.ss.findLeastGreaterThanOrEqual(key)
```

Let's say collection has `1, 3, 5`. If key is 3, then return 3 (matched element). If key is 4, then return 5 (the next element of 4's insertion position).
It is similar to C++ STL lower_bound algorithm.

### delete element by iterator (cursor) or key
https://github.com/redboltz/number-allocator/blob/af3e1542b01910626aa9237f0ebb8f2493c2a288/lib/number-allocator.js#L99
```js
      this.ss.delete(it.value)
```

### insert element
https://github.com/redboltz/number-allocator/blob/af3e1542b01910626aa9237f0ebb8f2493c2a288/lib/number-allocator.js#L136
```js
    this.ss.push(new Interval(low, num - 1))
```

### get matched element otherwise the previous element
https://github.com/redboltz/number-allocator/blob/af3e1542b01910626aa9237f0ebb8f2493c2a288/lib/number-allocator.js#L157
```js
  const it = this.ss.findLeastGreaterThanOrEqual(key)
```
Let's say collection has `1, 3, 5`. If key is 3, then return 3 (matched element). If key is 4, then return 3 (the previous element of 4's insertion position).

It can be achieved `get matched element otherwise the next element` and then move the cursor to the previous element
if cursor move is supported.

### clear
https://github.com/redboltz/number-allocator/blob/af3e1542b01910626aa9237f0ebb8f2493c2a288/lib/number-allocator.js#L230
```js
  this.ss.clear()
```
Overwriting by new object is acceptable solution.

----

I found https://www.npmjs.com/package/js-sdsl . It asmost cover all functionalities. But it doesn't support `get matched element otherwise the previous element` so far. So I wrote pull request for that https://github.com/ZLY201/js-sdsl/pull/2
And it has been merged just now.

So I started migrating SortedSet from collections.js to Set from js-sdsl.

# The current situation
- LRUmap
   - still looking for the candidate
- SortedSet
   - migrating to js-sdsl. If it is finished, dependency of collections.js is removed

**Comment by redboltz** [comment]
#1394 replaced SortedSet from collections to js-sdsl. So one of collections dependency is removed.
I'm looking for LRU map replacement candidate but I couldn't find, so far.
Information is very welcome.
As I commented https://www.npmjs.com/package/quick-lru satisfies functionality. If it works with common js (cjs) , it is good but I guess that it is not possible.

**Comment by YoDaMa** [comment]
release 4.3.3 should resolve this issue. please let me know.

**Comment by dgg** [comment]
I'll look into it tomorrow in the morning and let you know if 4.3.3 solves
it.

Thanks

**Comment by tukusejssirs** [comment]
> release 4.3.3 should resolve this issue. please let me know.

I does not solve the issue describe in [this comment above](https://github.com/mqttjs/MQTT.js/issues/1392#issuecomment-1005682846).

The issue is that `collections` patches Node methods like `Map`, `Set`, `Array`. The only solution I see to get rid of that package. Until then, `collections` (and thus `mqtt`) breaks many packages.

Once again: this issue is better described by @b4nan in [this comment](https://github.com/mikro-orm/mikro-orm/discussions/2597#discussioncomment-1912286) and following ones.

**Comment by redboltz** [comment]
I found good candidate of LRU map container.
It is https://www.npmjs.com/package/lru
However, it doesn't have accessing LRU element method. It is required by MQTT.js.
So I created https://github.com/chriso/lru/pull/39
If it would be merged and released, then the collections dependency would be completely removed.

**Comment by redboltz** [comment]
It seems that I found better one.
It is  https://www.npmjs.com/package/lru-cache
I can get `get least used element` using `lrumap.keys()[lrumap.length - 1]`.
( I need only getting key)

I just started replacing.

**Comment by YoDaMa** [comment]
@tukusejssirs yeah we're doing a full rewrite so we can make sure the testing infra protects changes in the future from breaking things like this. rn testing is sh*t unfortunately... that is why problems like this keep occuring.

**Comment by YoDaMa** [comment]
let me know if 4.3.4 fixes this issue now...

**Comment by tukusejssirs** [comment]
It works as expected! Thanks, @YoDaMa! :100: :pray:

**Comment by YoDaMa** [comment]
closing issue as resolved.
