### ISSUE TITLE
Enhance Environment Detection to Support Shared Workers

### ISSUE THREAD

**Issue by hibrandonevans** [mqttjs/MQTT.js#1743]
## Issue Description
I've encountered an issue where mqtt.js does not correctly identify the environment when running in a Shared Worker context. This leads to incorrect behavior as the library assumes it's not in a browser-like environment.

## Steps to Reproduce
1. Set up mqtt.js in a Shared Worker environment.
2. Notice that mqtt.js fails to recognize this environment correctly.

## Expected Behavior
I would expect mqtt.js to correctly identify the Shared Worker environment, similar to how it detects Dedicated Worker or standard browser environments.

## Actual Behavior
Currently, mqtt.js does not recognize the Shared Worker environment, which can lead to incorrect assumptions and functionality within the library.

## Possible Solution
I believe this issue can be addressed by enhancing the environment detection logic in mqtt.js to include checks for `SharedWorkerGlobalScope`. I am willing to work on this and contribute a PR if the maintainers are open to it.

![image](https://github.com/mqttjs/MQTT.js/assets/112993120/36dabf10-ddde-4043-b77d-02fc6c490ed6)

```typescript
// src/lib/is-browser.ts
const isBrowser =
	(typeof window !== 'undefined' && typeof window.document !== 'undefined') ||
	// eslint-disable-next-line no-restricted-globals
	(typeof self === 'object' &&
		// eslint-disable-next-line no-restricted-globals
		self.constructor &&
		// eslint-disable-next-line no-restricted-globals
		self.constructor.name === 'DedicatedWorkerGlobalScope') || // is web worker? 
	(typeof navigator !== 'undefined' && navigator.product === 'ReactNative') // while navigator.product is deprecated

export default isBrowser
```

**Comment by robertsLando** [comment]
@hibrandonevans PR?

**Comment by hibrandonevans** [comment]
> @hibrandonevans PR?

Yes, I've submitted the PR for this issue. Here's the [link](https://github.com/mqttjs/MQTT.js/pull/1744).

**Comment by gd5paisa** [comment]
I am still facing similar issue even with the fix. 

Uncaught (in promise) ReferenceError: window is not defined
    at mqtt.esm.js:2:1
    at mqtt.esm.js:1:1
    at mqtt.esm.js:14:1
    at mqtt.esm.js:1:1
    at mqtt.esm.js:14:1
    at mqtt.esm.js:1:1
    at ./node_modules/mqtt/dist/mqtt.esm.js (mqtt.esm.js:14:1)
    at options.factory (react refresh:6:1)
    at __webpack_require__ (bootstrap:24:1)
    at fn (hot module replacement:62:1)

I am calling it via Webworker.

**Comment by robertsLando** [comment]
@gd5paisa Are you using a custom version? Because actially that's not released yet

**Comment by robertsLando** [comment]
Fixed by #1744

**Comment by hibrandonevans** [comment]
Hello, when using the latest v5.3.1, I found that it still cannot work properly in the worker:
![image](https://github.com/mqttjs/MQTT.js/assets/112993120/e1687fa4-ee4f-44e8-a760-f1a72d7c7527)


The reason for this was found to be that during packaging, 'global' was replaced with 'window'
![image (1)](https://github.com/mqttjs/MQTT.js/assets/112993120/b6a4f121-265b-4ddf-9eb0-076edcb00c32)
![image](https://github.com/mqttjs/MQTT.js/assets/112993120/887fcf12-d2f9-4b3e-b706-8d81bd5cdc2f)

This is the [fix PR](https://github.com/mqttjs/MQTT.js/pull/1747), please check it.
