### ISSUE TITLE
Store not processing messages between restarts

### ISSUE THREAD

**Issue by nmec** [mqttjs/MQTT.js#398]
## Summary

Unsent messages are not processed from the store after restart.
## Steps to reproduce
1. Client loses connection
2. Client attempts to send message
3. Client process exits and restarts (e.g power loss)
4. Client reconnects
## Expected behaviour

Unsent messages are persisted in the store between restarts, and resent when the client restarts and reconnects to the broker.
## Actual behaviour

Unsent messages are not sent to the broker after restarting, despite using a store.
## Notes

Using QoS 1 and mqtt-level-store for persistence.

Possibly related to #343

**Comment by mcollina** [comment]
Can you please upload a code snippet that exhibit the issue?

**Comment by nmec** [comment]
```js
'use strict';

const debug = require('debug')('publisher');
const mqtt = require('mqtt');
const mqttLevelStore = require('mqtt-level-store');
const manager = mqttLevelStore('data/leveldb');
const host = process.env.MQTT_HOST || 'mqtt://localhost';
const client = mqtt.connect(host, {
  username: process.env.MQTT_USER || 'admin',
  password: process.env.MQTT_PASS || 'pass',
  incomingStore: manager.incoming,
  outgoingStore: manager.outgoing,
  keepalive: 60
});

const publish = (data) => {
  const payload = JSON.stringify(data);
  const topic = 'example';
  client.publish(topic, payload, {
    qos: 1
  }, () => {
    debug('published', topic, payload);
  });
};

module.exports = publish;
```

**Comment by mcollina** [comment]
Whoaa, right! Thanks for catching this, it has been around for a bit. The problem is that the message is not being stored if we are not connect, but just put in the in-memory queue: 
https://github.com/mqttjs/MQTT.js/blob/master/lib/client.js#L598-L610
https://github.com/mqttjs/MQTT.js/blob/master/lib/client.js#L48-L55

This needs to be reworked so that we are actually storing things when we are offline. Would you like to send a PR?

**Comment by nmec** [comment]
I'd love to have this functionality but I'm not sure how much of a priority I can make it at the moment. From a brief look at `client.js` this would probably be a substantial reworking.

**Comment by mcollina** [comment]
It might have been fixed. If not, feel free to reopen.

**Comment by johan13** [comment]
The bug is still there as far as I can tell.

Is there any point in offering the option to provide a persistent `Store` implementation for the `outgoingStore` if the stored messages are not sent when the process restarts?

**Comment by mcollina** [comment]
@johan13 would you mind to open a new issue, with a script to reproduce?

**Comment by johan13** [comment]
Thanks @behrad! Looks great. I will give it a try next week.
