### ISSUE TITLE
Cannot connect VerneMQ Broker using v2.0.1

### ISSUE THREAD

**Issue by heppoko-samurai** [mqttjs/MQTT.js#482]
Hi, 
I'm using the VerneMQ (https://vernemq.com/) MQTT Broker. 
When I use "v1.14.1" of MQTT.js, I can connect to VerneMQ MQTT Broker  from browser (using Websocket). But I can NOT connect when I use latest version (v2.0.1).

Information

- Browser: Google Chrome (Windows10 PC)
- MQTT.js: browserMqtt.js  (about https://github.com/mqttjs/MQTT.js#browser)
- Broker: VerneMQ

````
var id = Math.floor((new Date()).getTime() / 1000).toString();

// Connect to VerneMQ Broker.
var client = mqtt.connect('ws://xxxxxxx.vernemq-broker.com:8883/mqtt', {
  clientId: id
});

client.on('connect', function(c) {
  console.log('connected');
  client.publish('mqtt/demo', 'hello world!');
});

client.on('close', function(c) {
  console.log('closed');
});

// Set subscrive
client.subscribe('mqtt/demo');

client.on('message', function(topic, payload) {
  console.log([topic, payload].join(': '));
//  client.end();
});
````

**Comment by RangerMauve** [comment]
Are there any errors being thrown in the console?

**Comment by heppoko-samurai** [comment]
No error message is shown in my console...
When I set "connect", "close" and "reconnect" event handler, I got the "close" and "reconnect" event.

Thank you.

**Comment by heppoko-samurai** [comment]
Thank you for update.
I made the browerMqtt.js using the latest code (2.1.1) and tried to connect to VerneMQ broker, but I cannot connect, yet... 

Addition: 

1.  when I use this (2.1.1),  I cannot connect mosquitto, too - ws://test.mosquitto.org:8080)
2.  I see the following error message on the browser console.
> WebSocket connection to 'ws://test.mosquitto.org:8080/' failed: Connection closed before receiving a handshake response

Thank you,

**Comment by mcollina** [comment]
This is fixed in: https://github.com/maxogden/websocket-stream/pull/100, which has not hit npm yet.

**Comment by mcollina** [comment]
Should be fixed in 2.1.2. Please check and let me know.

**Comment by andyfenelon** [comment]
trying this with browserify & "mqtt": "^2.1.2"
still getting the error

> bundle.js:12089 WebSocket connection to 'ws://test.mosquitto.org:8080/mqtt' failed: Connection closed before receiving a handshake response

```
const mqtt = require('mqtt')
const client  = mqtt.connect('ws://test.mosquitto.org:8080/mqtt')
// also tried const client  = mqtt.connect('ws://test.mosquitto.org:8080')

client.subscribe('mitsuruog')

client.on('message', function (topic, message) {
  console.log(message.toString());
})
```

**Comment by mcollina** [comment]
Test version 2.1.3.

**Comment by andyfenelon** [comment]
yup 2.1.3 is working. thanks!

**Comment by heppoko-samurai** [comment]
Sorry for late response.
I have confirmed that it (2.1.3) working fine.
Thank you!
